devel: drop precise
ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    Your version of git is older than 1.8.3.1 and has bugs which will break builds. Please install a newer version of git.